### ISSUE TITLE
NoClassDefFoundError: cn/nukkit/level/sound/Sound

### ISSUE THREAD

**Issue by JPaulMora** [PikyCZ/NovaMobs#87]
````
23:56:29 [ALERT] java.lang.RuntimeException: java.lang.NoClassDefFoundError: cn/nukkit/level/sound/Sound
	at cn.nukkit.plugin.PluginManager.enablePlugin(PluginManager.java:450)
	at cn.nukkit.Server.enablePlugin(Server.java:633)
	at cn.nukkit.Server.enablePlugins(Server.java:622)
	at cn.nukkit.Server.<init>(Server.java:398)
	at cn.nukkit.Nukkit.main(Nukkit.java:102)
Caused by: java.lang.NoClassDefFoundError: cn/nukkit/level/sound/Sound
	at java.lang.Class.getDeclaredFields0(Native Method)
	at java.lang.Class.privateGetDeclaredFields(Class.java:2583)
	at java.lang.Class.getField0(Class.java:2975)
	at java.lang.Class.getField(Class.java:1701)
	at cn.nukkit.entity.Entity.registerEntity(Entity.java:715)
	at com.pikycz.novamobs.NovaMobs.registerEntity(NovaMobs.java:151)
	at com.pikycz.novamobs.NovaMobs.onEnable(NovaMobs.java:90)
	at cn.nukkit.plugin.PluginBase.setEnabled(PluginBase.java:89)
	at cn.nukkit.plugin.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:113)
	at cn.nukkit.plugin.PluginManager.enablePlugin(PluginManager.java:446)
	... 4 more
Caused by: java.lang.ClassNotFoundException: cn.nukkit.level.sound.Sound
	at cn.nukkit.plugin.PluginClassLoader.findClass(PluginClassLoader.java:34)
	at cn.nukkit.plugin.PluginClassLoader.findClass(PluginClassLoader.java:28)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 14 more
````

It seems NukkitX changed the class to `cn/nukkit/level/Sound.java` A simple recompile should make it work alright.

**Comment by PikyCZ** [comment]
i know ..

**Comment by JPaulMora** [comment]
So.. could you push a quick build :)

**Comment by PikyCZ** [comment]
At 2:48 am? .. lol no wait..

**Comment by JPaulMora** [comment]
Hey I tried building it with no success, any help doing so?
Thanks

**Comment by Creeperface01** [comment]
Blame piky

**Comment by PikyCZ** [comment]
@JPaulMora  try now

**Comment by JPaulMora** [comment]
Try releases or building?

**Comment by PikyCZ** [comment]
i do not make release for this small fix lol

**Comment by JPaulMora** [comment]
I did get a jar but can't get it recognized on Nukkit. Do you use netbeans or eclipse?

**Comment by PikyCZ** [comment]
Netbeans

**Comment by PikyCZ** [comment]
fixed
